GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/3

###
DELETE http://localhost:3001/api/persons/2

###
POST  http://localhost:3001/api/persons
Content-Type: application/json

{ 
      "name": "Rangasai K R", 
      "number": "84-2365-4242"
}

###
PUT  http://localhost:3001/api/persons/616431826f98a24d74b0d128
Content-Type: application/json

{ 
      "name": "Rangasai K R", 
      "number": "84"
}